version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qg_airsoft_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    container_name: qg_airsoft_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qg_airsoft
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
